spring:
  datasource:
    url: jdbc:mysql://tk3mehkfmmrhjg0b.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/guytjzpp2f3u7y7m?reconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: upjn2kkzdtrhvwgi
    password: myk6eyzouzao4fil
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

endpoints:
  baseUrl: http://localhost:8080
  clientUrl: http://localhost:4200