spring:
  datasource:
    url: jdbc:mysql://deofis.c0j3cq5bdbwq.eu-west-2.rds.amazonaws.com/deofis_qa
    username: user_qa
    password: userqa1224
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: Deofis1224
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://api.deofisdev.online
  clientUrl: https://deofisdev.online

jwt:
  expirationInMillis: 900000

server:
  port: ${PORT:5000}