spring:
  datasource:
    url: jdbc:mysql://deofis.c0j3cq5bdbwq.eu-west-2.rds.amazonaws.com/deofis_qa
    username: user_qa
    password: userqa1224
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: Deofisdev1224
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://api.deofisdev.online
  clientUrl: https://deofisdev.online

amazon:
  s3:
    bucketName: deofis-images-bucket
    endpoint: https://deofis-images-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: AKIAZ67T4O5CQ2MJ2BHE
    secretKey: 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

jwt:
  expirationInMillis: 900000

server:
  port: ${PORT:5000}