spring:
  datasource:
    url: jdbc:mysql://tk3mehkfmmrhjg0b.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/guytjzpp2f3u7y7m?reconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: upjn2kkzdtrhvwgi
    password: myk6eyzouzao4fil
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: ENC(GHcd9hKRmbT/kPPNHJhA+Gx9ZhHmKSFh)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://deofis-tienda-apirest.herokuapp.com
  clientUrl: https://wantfrom-tienda.web.app

amazon:
  s3:
    bucketName: deofis-images-bucket
    endpoint: https://deofis-images-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: ENC(KDAOVAGwgVlAy3p81kVkiM8E+075tCb3D9ZIkMFrcSc=)
    secretKey: ENC(M/rXjb895VoXdgvzdPlorMfTOmhQftQFGOCc8x+YvDYsZLe0TnTCScBQmG7rbEto8uSvH76aNrc=)

jwt:
  expirationInMillis: 900000

server:
  port: ${PORT:8080}

jasypt:
  encryptor:
    password: deofis1224