spring:
  datasource:
    url: jdbc:mysql://b91f2b93630081:233cb850@us-cdbr-east-02.cleardb.com:3306/heroku_ff337ed7022a9b9?reconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: b91f2b93630081
    password: 233cb850
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

endpoints:
  baseUrl: http://localhost:8080
  clientUrl: http://localhost:4200

jwt:
  expirationInMillis: 900000