spring:
  datasource:
    url: jdbc:mysql://deofis.c0j3cq5bdbwq.eu-west-2.rds.amazonaws.com/deofis_qa
    username: user_qa
    password: ENC(2ns5ABYULg5Mg6srSA5tefYRlkqAebbl)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: ENC(43ObyGBU+p+d7yD3/Qq9eYoVocoDxeYk)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://api.deofisdev.online
  clientUrl: https://deofisdev.online

amazon:
  s3:
    bucketName: deofis-images-bucket
    endpoint: https://deofis-images-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: ENC(G8IyhZeQLap2yXU26oMJmcfmwkeEKfvIFId40bmsUvs=)
    secretKey: ENC(c/9xHbxVjYPRv5i0krzKvejyw/0L2gB6GQ9bCIvy6adYN67uK7WTJGwBwHUogDjhSw6MQyZdRVM=)

jwt:
  expirationInMillis: 900000

server:
  port: ${PORT:5000}