spring:
  datasource:
    url: jdbc:mysql://deofis.ciu67zuuk0kj.eu-west-2.rds.amazonaws.com:3306/deofis_qa
    username: user_qa
    password: userqa1224
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  expirationInMillis: 900000