spring:
  datasource:
    url: jdbc:mysql://tk3mehkfmmrhjg0b.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/guytjzpp2f3u7y7m?reconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: upjn2kkzdtrhvwgi
    password: myk6eyzouzao4fil
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: Deofis1224
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://deofis-tienda-apirest.herokuapp.com
  clientUrl: https://wantfrom-tienda.web.app